<?php

return [

    'groups' => [
        'analytics' => [
            'label' => 'Analytiques',
            'modules' => [
                'analytics' => 'Tableau de bord analytiques',
            ],
        ],
        'tickets' => [
            'label' => 'Mes Tickets',
            'modules' => [
                'tickets.index' => 'Tous les tickets',
                'tickets.today' => 'Tickets du jour',
                'tickets.pending' => 'Tickets en attente',
                'tickets.validated' => 'Tickets validés',
                'tickets.verified' => 'Tickets vérifiés',
                'tickets.paid' => 'Tickets payés',
                'tickets.modifications' => 'Modifications de tickets',
                'tickets.search' => 'Recherche avancée',
                'tickets.destroy' => 'Supprimer un ticket',
            ],
        ],
        'finance' => [
            'label' => 'Gestion financière',
            'modules' => [
                'prix-unitaires' => 'Prix unitaire',
                'bordereaux' => 'Bordereaux',
                'financements' => 'Financements',
                'financements.valider' => 'Valider demandes de financement',
                'prets' => 'Prêts',
                'usines.amounts' => 'Montants usines',
                'comptes-agents' => 'Comptes agents',
                'comptes-groupes' => 'Comptes groupes',
            ],
        ],
        'utilisateurs' => [
            'label' => 'Gestion des utilisateurs',
            'modules' => [
                'utilisateurs.index' => 'Liste des utilisateurs',
                'utilisateurs.roles' => 'Gestion des rôles',
            ],
        ],
        'gestion' => [
            'label' => 'Gestion',
            'modules' => [
                'groupes' => 'Groupes',
                'agents' => 'Agents',
                'commis' => 'Commis',
                'vehicules' => 'Véhicules',
            ],
        ],
        'usines' => [
            'label' => 'Gestion des usines',
            'modules' => [
                'usines' => 'Liste des usines',
                'usines.montants' => 'Points des usines',
                'usines.financements' => 'Financement des usines',
            ],
        ],
        'ponts' => [
            'label' => 'Gestion des ponts',
            'modules' => [
                'ponts.index' => 'Liste des ponts',
                'ponts.types' => 'Types de ponts',
                'ponts.regions' => 'Gestion des régions',
                'ponts.location' => 'Localisation des ponts',
            ],
        ],
        'plantations' => [
            'label' => 'Gestion des plantations',
            'modules' => [
                'plantations.index' => 'Liste des plantations',
                'plantations.collecteurs' => 'Liste des collecteurs',
                'plantations.collecteurs.show' => 'Détail collecteur',
                'plantations.regions' => 'Régions',
                'plantations.zones' => 'Zones',
                'plantations.doublons' => 'Gestion des doublons',
            ],
        ],
        'sorties' => [
            'label' => 'Gestion des sorties',
            'modules' => [
                'sorties.demandes' => 'Liste des demandes',
                'sorties.pending' => 'Demandes en attente',
                'sorties.validated' => 'Demandes validées',
                'sorties.diverses' => 'Sorties diverses',
            ],
        ],
        'caisse' => [
            'label' => 'Gestion caisse',
            'modules' => [
                'caisse.solde' => 'Solde de la caisse',
                'caisse.approvisionnement' => 'Approvisionnement',
                'caisse.paiements' => 'Effectuer un paiement',
                'caisse.banques' => 'Banques',
            ],
        ],
        'recus' => [
            'label' => 'Gestion des reçus',
            'modules' => [
                'recus.tickets' => 'Reçu paiement tickets/bordereaux',
                'recus.demandes' => 'Reçu des paiements demandes et diverses',
            ],
        ],
    ],

    'route_map' => [
        'tickets.index' => 'tickets.index',
        'tickets.today' => 'tickets.today',
        'tickets.pending' => 'tickets.pending',
        'tickets.validated' => 'tickets.validated',
        'tickets.verified' => 'tickets.verified',
        'tickets.paid' => 'tickets.paid',
        'tickets.modifications' => 'tickets.modifications',
        'tickets.search' => 'tickets.search',
        'tickets.update' => 'tickets.modifications',
        'tickets.validate' => 'tickets.pending',
        'tickets.validate-bulk' => 'tickets.pending',
        'tickets.store' => 'tickets.index',
        'tickets.pdf-by-usine' => 'tickets.index',
        'tickets.pdf-bordereau' => 'tickets.index',
        'tickets.export-all' => 'tickets.index',
        'tickets.export-period' => 'tickets.index',
        'tickets.destroy' => 'tickets.destroy',

        'prix-unitaires.index' => 'prix-unitaires',
        'prix-unitaires.store' => 'prix-unitaires',
        'prix-unitaires.update' => 'prix-unitaires',
        'bordereaux.index' => 'bordereaux',
        'bordereaux.preview' => 'bordereaux',
        'bordereaux.store' => 'bordereaux',
        'bordereaux.validate' => 'bordereaux',
        'bordereaux.destroy' => 'bordereaux',
        'bordereaux.pdf' => 'bordereaux',

        'financements.index' => 'financements',
        'financements.show' => 'financements',
        'financements.pdf' => 'financements',
        'financements.store' => 'financements',
        'financements.valider' => 'financements.valider',
        'comptes-agents.demande-financement.store' => 'comptes-agents',
        'comptes-agents.demandes-avance.payment' => 'comptes-agents',

        'prets.index' => 'prets',
        'prets.show' => 'prets',
        'prets.store' => 'prets',

        'usines.amounts' => 'usines.amounts',
        'usines.amounts.show' => 'usines.amounts',
        'usines.amounts.payments.pdf' => 'usines.amounts',
        'usines.amounts.payment' => 'usines.amounts',

        'comptes-agents.index' => 'comptes-agents',
        'comptes-agents.show' => 'comptes-agents',
        'comptes-agents.bordereaux.payment' => 'comptes-agents',
        'comptes-agents.transactions.pdf' => 'comptes-agents',

        'comptes-groupes.index' => 'comptes-groupes',
        'comptes-groupes.show' => 'comptes-groupes',
        'comptes-groupes.bordereaux.payment' => 'comptes-groupes',

        'utilisateurs.index' => 'utilisateurs.index',
        'utilisateurs.store' => 'utilisateurs.index',
        'utilisateurs.show' => 'utilisateurs.index',
        'utilisateurs.update' => 'utilisateurs.index',
        'utilisateurs.password.update' => 'utilisateurs.index',
        'utilisateurs.password.reset' => 'utilisateurs.index',
        'utilisateurs.inline-update' => 'utilisateurs.index',
        'utilisateurs.toggle-statut' => 'utilisateurs.index',
        'utilisateurs.destroy' => 'utilisateurs.index',
        'utilisateurs.photo.edit' => 'utilisateurs.index',
        'utilisateurs.photo.store' => 'utilisateurs.index',
        'utilisateurs.avatar' => 'utilisateurs.index',

        'role-permissions.index' => 'utilisateurs.roles',
        'role-permissions.edit' => 'utilisateurs.roles',
        'role-permissions.update' => 'utilisateurs.roles',

        'groupes.index' => 'groupes',
        'groupes.store' => 'groupes',
        'groupes.show' => 'groupes',
        'groupes.credentials.update' => 'groupes',

        'agents.index' => 'agents',
        'agents.autocomplete' => 'agents',
        'agents.store' => 'agents',
        'agents.show' => 'agents',
        'agents.documents.store' => 'agents',
        'agents.documents.show' => 'agents',
        'agents.update' => 'agents',
        'agents.associate-pont' => 'agents',
        'agents.inline-update' => 'agents',
        'agents.destroy' => 'agents',

        'commis.index' => 'commis',
        'commis.agents-autocomplete' => 'commis',
        'commis.ponts-for-agent' => 'commis',
        'commis.store' => 'commis',
        'commis.update' => 'commis',
        'commis.destroy' => 'commis',

        'usines.index' => 'usines',
        'usines.store' => 'usines',
        'usines.update' => 'usines',
        'usines.location' => 'usines',
        'usines.montants' => 'usines.montants',
        'usines.montants.show' => 'usines.montants',
        'usines.montants.entrees.store' => 'usines.montants',
        'usines.montants.day.pdf' => 'usines.montants',
        'usines.montants.payment' => 'usines.montants',
        'usines.montants.payments.pdf' => 'usines.montants',
        'usines.financements.index' => 'usines.financements',
        'usines.financements.show' => 'usines.financements',
        'usines.financements.store' => 'usines.financements',

        'vehicules.index' => 'vehicules',
        'vehicules.store' => 'vehicules',
        'vehicules.update' => 'vehicules',
        'vehicules.destroy' => 'vehicules',
        'vehicules.bulk-destroy' => 'vehicules',

        'sorties.demandes.index' => 'sorties.demandes',
        'sorties.demandes.store' => 'sorties.demandes',
        'sorties.demandes.update' => 'sorties.demandes',
        'sorties.demandes.destroy' => 'sorties.demandes',

        'sorties.pending.index' => 'sorties.pending',
        'sorties.pending.approve' => 'sorties.pending',
        'sorties.pending.reject' => 'sorties.pending',

        'sorties.diverses.index' => 'sorties.diverses',
        'sorties.diverses.store' => 'sorties.diverses',
        'sorties.diverses.destroy' => 'sorties.diverses',

        'caisse.banques.index' => 'caisse.banques',
        'caisse.banques.approvisionnement-caisse.index' => 'caisse.banques',
        'caisse.banques.approvisionnement-caisse.store' => 'caisse.banques',
        'caisse.banques.store' => 'caisse.banques',
        'caisse.banques.show' => 'caisse.banques',
        'caisse.banques.approvisionnement' => 'caisse.banques',
        'caisse.banques.paiement-usine' => 'caisse.banques',
        'caisse.banques.update' => 'caisse.banques',
        'caisse.banques.destroy' => 'caisse.banques',
        'caisse.solde.index' => 'caisse.solde',
        'caisse.approvisionnement.store' => 'caisse.approvisionnement',
        'caisse.utilisable.update' => 'caisse.approvisionnement',
        'caisse.paiements.index' => 'caisse.paiements',
        'caisse.paiements.demandes.store' => 'caisse.paiements',
        'caisse.paiements.divers.store' => 'caisse.paiements',

        'recus.tickets.index' => 'recus.tickets',
        'recus.tickets.pdf' => 'recus.tickets',

        'ponts.index' => 'ponts.index',
        'ponts.types.index' => 'ponts.types',
        'ponts.types.store' => 'ponts.types',
        'ponts.types.update' => 'ponts.types',
        'ponts.types.destroy' => 'ponts.types',
        'ponts.regions.index' => 'ponts.regions',
        'ponts.regions.show' => 'ponts.regions',
        'ponts.regions.departements' => 'ponts.regions',
        'ponts.regions.map-data' => 'ponts.regions',
        'ponts.regions.ponts-map-data' => 'ponts.regions',
        'ponts.regions.store' => 'ponts.regions',
        'ponts.regions.import' => 'ponts.regions',
        'ponts.regions.update' => 'ponts.regions',
        'ponts.regions.destroy' => 'ponts.regions',
        'ponts.departements.index' => 'ponts.regions',
        'ponts.departements.show' => 'ponts.regions',
        'ponts.departements.map-data' => 'ponts.regions',
        'ponts.departements.import' => 'ponts.regions',
        'ponts.departements.sous-prefectures' => 'ponts.regions',
        'ponts.sous-prefectures.index' => 'ponts.regions',
        'ponts.sous-prefectures.show' => 'ponts.regions',
        'ponts.sous-prefectures.map-data' => 'ponts.regions',
        'ponts.sous-prefectures.import' => 'ponts.regions',
        'ponts.villages.index' => 'ponts.regions',
        'ponts.villages.store' => 'ponts.regions',
        'ponts.villages.update' => 'ponts.regions',
        'ponts.villages.destroy' => 'ponts.regions',
        'ponts.villages.departements-options' => 'ponts.regions',
        'ponts.villages.sous-prefectures-options' => 'ponts.regions',
        'ponts.location' => 'ponts.location',
        'ponts.location.region' => 'ponts.location',
        'ponts.regions.departements-options' => 'ponts.index',
        'ponts.departements.sous-prefectures-options' => 'ponts.index',
        'ponts.sous-prefectures.villages-options' => 'ponts.index',
        'ponts.store' => 'ponts.index',
        'ponts.commis-options' => 'ponts.index',
        'ponts.update' => 'ponts.index',
        'ponts.destroy' => 'ponts.index',

        'plantations.index' => 'plantations.index',
        'plantations.show' => 'plantations.index',
        'plantations.edit' => 'plantations.index',
        'plantations.api' => 'plantations.index',
        'plantations.collecteurs' => 'plantations.collecteurs',
        'plantations.collecteurs.show' => 'plantations.collecteurs',
        'plantations.collecteurs.api' => 'plantations.collecteurs',
        'plantations.collecteurs.photo' => 'plantations.collecteurs',
        'plantations.regions' => 'plantations.regions',
        'plantations.regions.api' => 'plantations.regions',
        'plantations.zones' => 'plantations.zones',
        'plantations.zones.api' => 'plantations.zones',
        'plantations.doublons' => 'plantations.doublons',
        'plantations.doublons.api' => 'plantations.doublons',
    ],

    'module_routes' => [
        'analytics' => 'tickets.index',
        'tickets.index' => 'tickets.index',
        'tickets.today' => 'tickets.today',
        'tickets.pending' => 'tickets.pending',
        'tickets.validated' => 'tickets.validated',
        'tickets.verified' => 'tickets.verified',
        'tickets.paid' => 'tickets.paid',
        'tickets.modifications' => 'tickets.modifications',
        'tickets.search' => 'tickets.search',
        'prix-unitaires' => 'prix-unitaires.index',
        'bordereaux' => 'bordereaux.index',
        'financements' => 'financements.index',
        'financements.valider' => 'financements.index',
        'prets' => 'prets.index',
        'usines.amounts' => 'usines.amounts',
        'comptes-agents' => 'comptes-agents.index',
        'comptes-groupes' => 'comptes-groupes.index',
        'utilisateurs.index' => 'utilisateurs.index',
        'utilisateurs.roles' => 'role-permissions.index',
        'groupes' => 'groupes.index',
        'agents' => 'agents.index',
        'commis' => 'commis.index',
        'usines' => 'usines.index',
        'usines.montants' => 'usines.montants',
        'usines.financements' => 'usines.financements.index',
        'vehicules' => 'vehicules.index',
        'sorties.demandes' => 'sorties.demandes.index',
        'sorties.pending' => 'sorties.pending.index',
        'sorties.validated' => 'sorties.validated.index',
        'sorties.diverses' => 'sorties.diverses.index',
        'caisse.banques' => 'caisse.banques.index',
        'caisse.solde' => 'caisse.solde.index',
        'caisse.approvisionnement' => 'caisse.solde.index',
        'caisse.paiements' => 'caisse.paiements.index',
        'recus.tickets' => 'recus.tickets.index',
        'recus.demandes' => 'recus.demandes.index',
        'ponts.index' => 'ponts.index',
        'ponts.types' => 'ponts.types.index',
        'ponts.regions' => 'ponts.regions.index',
        'ponts.location' => 'ponts.location',
        'plantations.index' => 'plantations.index',
        'plantations.collecteurs' => 'plantations.collecteurs',
        'plantations.regions' => 'plantations.regions',
        'plantations.zones' => 'plantations.zones',
        'plantations.doublons' => 'plantations.doublons',
    ],

    'home_by_role' => [
        'caissiere' => 'comptes-groupes',
    ],

    'defaults' => [
        'admin' => '*',
        'directeur' => [
            'analytics', 'tickets.index', 'tickets.today', 'tickets.pending', 'tickets.validated',
            'tickets.verified', 'tickets.paid', 'tickets.modifications', 'tickets.search', 'tickets.destroy',
            'prix-unitaires', 'bordereaux', 'financements', 'financements.valider', 'prets', 'usines.amounts',
            'comptes-agents', 'comptes-groupes', 'utilisateurs.index',
            'groupes', 'agents', 'commis', 'usines', 'usines.montants', 'usines.financements', 'vehicules',
        ],
        'validateur' => [
            'analytics', 'tickets.index', 'tickets.today', 'tickets.pending', 'tickets.validated',
            'tickets.verified', 'tickets.modifications', 'tickets.search',
        ],
        'operateur' => [
            'tickets.index', 'tickets.today', 'tickets.search',
        ],
        'caissiere' => [
            'analytics', 'tickets.index', 'tickets.paid', 'tickets.search',
            'prix-unitaires', 'bordereaux', 'financements', 'financements.valider', 'prets',
            'comptes-agents', 'comptes-groupes', 'usines.amounts',
            'caisse.solde', 'caisse.approvisionnement', 'caisse.paiements', 'caisse.banques',
            'recus.tickets',
            'sorties.demandes', 'sorties.pending', 'sorties.diverses',
        ],
    ],

];
